# Duplicate data

In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = {"name":['a', 'b', 'c', 'd', 'a', 'c'], "eng":[8, 7, 6, 2, 8, 6], "hindi":[2, 3, 5, 9, 2, 5]}

df = pd.DataFrame(data)
df

  name  eng  hindi
0    a    8      2
1    b    7      3
2    c    6      5
3    d    2      9
4    a    8      2
5    c    6      5

In [3]:
df['duplicated'] = df.duplicated()
df

  name  eng  hindi  duplicated
0    a    8      2       False
1    b    7      3       False
2    c    6      5       False
3    d    2      9       False
4    a    8      2        True
5    c    6      5        True

In [4]:
df.drop_duplicates(keep='first', inplace=True)

In [5]:
df

  name  eng  hindi  duplicated
0    a    8      2       False
1    b    7      3       False
2    c    6      5       False
3    d    2      9       False
4    a    8      2        True
5    c    6      5        True

In [6]:
# Replace and Datatype Change

In [7]:
df = pd.read_csv('../../Dataset/loan.csv')
df.head(3)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y

In [8]:
# here we can show 'Dependents' Column have numeric value it's be int or floting format so we need to convert it
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [9]:
df['Dependents'].fillna(df['Dependents'].mode()[0], inplace=True)

In [10]:
df['Dependents'].unique()

array(['0', '1', '2', '3+'], dtype=object)

In [11]:
df['Dependents'].value_counts()

Dependents
0     360
1     102
2     101
3+     51
Name: count, dtype: int64

In [12]:
df['Dependents'].replace("3+","3", inplace=True)

In [13]:
df['Dependents'].value_counts()

Dependents
0    360
1    102
2    101
3     51
Name: count, dtype: int64

In [14]:
# it is still show Object Datatype means we should need convert it to int
df['Dependents'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 614 entries, 0 to 613
Series name: Dependents
Non-Null Count  Dtype
--------------  -----
614 non-null    object
dtypes: object(1)
memory usage: 4.9+ KB

In [15]:
df['Dependents'] = df['Dependents'].astype("int64")

In [16]:
# ok now it change to Int64
df['Dependents'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 614 entries, 0 to 613
Series name: Dependents
Non-Null Count  Dtype
--------------  -----
614 non-null    int64
dtypes: int64(1)
memory usage: 4.9 KB