# Imbalanced Data

In [32]:
# Imbalanced data in data science means the number of samples in each class is not equal.
# One class has many more examples, and another class has very few.

# The model becomes biased if there is only few catagory any one
# video ex. Airports on indian People

### Example

In [33]:
# Fraud detection → 99% normal, 1% fraud
# Medical diagnosis → 95% healthy, 5% sick
# Spam detection → 90% normal emails, 10% spam

## Techniques to handle inbalanced Data
### 1. **Random Under Sampling:** We will reduce the majority of the class so that it will have same no of as the minority
### 2. **Random Over Sampling:** We will increase the size of manority is inactive class to the size of majority class ie active.

## **1. Random Under Sampling**

In [34]:
# Random Under Sampling (RUS)

# Suppose you have imbalanced data:
# Example:
#   900 samples of class 0
#   100 samples of class 1
#
# The dataset is unbalanced because one class (0) is much larger.

# What Random Under Sampling does:
# - It removes (deletes) some data from the majority class (class 0)
# - It reduces the big class down to the size of the smaller class
#
# Example:
#   From 900 samples of class 0 → randomly keep only 100 samples
#   Class 1 already has 100 samples → keep all
#
# After RUS:
#   100 samples of class 0
#   100 samples of class 1
#   Balanced dataset!

# Why we use it:
# - To make machine learning models learn equally from both classes
# - To avoid bias toward the majority class

# Downside:
# - We lose some useful data because many samples of the majority class are removed.

In [35]:
df = pd.read_csv('../Dataset/Social_Network_Ads.csv')
df

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [36]:
df['Purchased'].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [37]:
x = df.iloc[:, :-1]
y = df.iloc[:, -1:]
x.head()

   Age  EstimatedSalary
0   19            19000
1   35            20000
2   26            43000
3   27            57000
4   19            76000

In [38]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [39]:
lr.fit(x_train, y_train)

LogisticRegression()

In [40]:
lr.score(x_test, y_test)*100

88.75

In [41]:
lr.predict([[46, 41000]])

array([0])

In [42]:
# Here we can show, our data train on that data but it's actually it's value give wrong
# there is 1 but our model show answer 0
# so now we are use RandomUnderSampler and then check

In [43]:
# we have only 143 numbers of value '1' so imblearn help us to do both value same count
# imblearn (Imbalanced-Learn) Explanation
# ---------------------------------------
# imblearn is a Python library used to handle imbalanced datasets in machine learning.
# In many real-world classification problems, the number of samples in each class is not equal.
# Example: Fraud detection, disease detection, spam detection — where positive cases are very low.
#
# If the dataset is imbalanced, the model may learn to predict only the majority class,
# which gives high accuracy but very poor performance for minority class.

In [44]:
from imblearn.under_sampling import RandomUnderSampler

In [45]:
ru = RandomUnderSampler()

In [46]:
ru_x, ru_y = ru.fit_resample(x, y)

In [47]:
ru_y.value_counts()

Purchased
0            143
1            143
Name: count, dtype: int64

In [48]:
# Here we can show we have only 1 data count is 143 so it randomly choolse only 143 data of 0.
# it's select whichever value is minimum than other and select random from more data insides

In [49]:
x_train, x_test, y_train, y_test = train_test_split(ru_x, ru_y, test_size=0.2, random_state=42)

In [50]:
lr.fit(x_train, y_train)

LogisticRegression()

In [51]:
lr.score(x_test, y_test)*100

77.58620689655173

In [52]:
lr.predict([[46, 41000]])

array([1])

In [53]:
# Now it's show answer 1 which actual answer so that mathod also increase accuraccy and give 
# right prediction than before.

## **2. Random Over Sampling**

In [54]:
# Random Over Sampling (ROS)

# Suppose your dataset is imbalanced:
# Example:
#   900 samples of class 0 (majority)
#   100 samples of class 1 (minority)

# What Random Over Sampling does:
# - It increases the number of samples in the minority class (class 1)
# - It does this by randomly repeating (copying) some of the minority samples
#
# Example:
#   Class 1 has 100 samples → randomly duplicate them until it becomes 900
#   Class 0 already has 900 → keep as it is

# After ROS:
#   900 samples of class 0
#   900 samples of class 1
#   Balanced dataset!

# Why we use it:
# - To give equal importance to both classes during training
# - It helps the model learn patterns from the minority class

# Downside:
# - Because it duplicates existing data, it can cause overfitting
#   (model learns the same samples again and again)

In [55]:
from imblearn.over_sampling import RandomOverSampler

In [56]:
ro = RandomOverSampler()

In [57]:
ro_x, ro_y = ro.fit_resample(x, y)

In [58]:
print(ro_y.value_counts())

Purchased
0            257
1            257
Name: count, dtype: int64

In [59]:
# In Over Sampling Repete our small amount of data Repete and repeted it to Almost same value

In [60]:
x_train, x_test, y_train, y_test = train_test_split(ro_x, ro_y, test_size=0.2, random_state=42)

In [61]:
lr.fit(x_train, y_train)

LogisticRegression()

In [62]:
lr.score(x_test, y_test)*100

87.37864077669903

In [63]:
lr.predict([[46, 41000]])

array([1])

In [64]:
# Now it's show answer 1 which actual answer so that mathod also increase accuraccy and give 
# right prediction than before.